kind = "web"
previewPath = "/"
title = "Trade Scheduler 2"
version = "1.0.0"
id = "artifacts/trade-scheduler"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19349

[services.development]
run = "pnpm --filter @workspace/trade-scheduler run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/trade-scheduler", "run", "build" ]
publicDir = "artifacts/trade-scheduler/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19349"
BASE_PATH = "/"
